[package]
name = "zokrates_embed"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]
edition = "2018"

[dependencies]
sapling-crypto = { path = "../deps/sapling-crypto" }
bellman = { path = '../deps/bellman' }
