#!/usr/bin/env bash

clean() {
    rm -rf out* witness *.json *.key *.raw
}

build() {
    (cd .. && ./build.sh)
}

compile() {
    ../target/debug/zokrates compile -i root.code
}

setup() {
    ../target/debug/zokrates setup
}

witness() {
    ../target/debug/zokrates compute-witness -a "$@"
}

generate() {
    ../target/debug/zokrates generate-proof
}

verify() {
    ../target/debug/zokrates verify-proof
}

err() {
    echo "Possible commands: clean, build, compile, setup, witness, generate, verify"
}

main() {
    local cmd; cmd=$1; shift
    [ -z "$cmd" ] && err && return 1
    $cmd "$@"
}

main "$@"
