#!/usr/bin/env bash

export ZOKRATES_PROVING_SCHEME=PGHR13

build() {
    (cd .. && cargo +nightly -Z package-features build --package zokrates_cli --features="libsnark")
}

unbuild() {
    (cd .. && cargo clean)
}

clean() {
    rm -rf out* witness *.json *.key *.raw
}

compile() {
    ../target/debug/zokrates compile -i root.code
}

setup() {
    ../target/debug/zokrates setup
}

witness() {
    [ -z $1 ] && echo "missing args" >&2 && return 1
    ../target/debug/zokrates compute-witness -a "$@"
}

generate() {
    ../target/debug/zokrates generate-proof
}

verify() {
    ../target/debug/zokrates verify-proof
}

move() {
    [ -z $1 ] && echo "missing args" >&2 && return 1
    mkdir -p "$1"
    cp verification.key* "$1"
    cp proof.json* "$1"
}

batch() {
    [ $# -ne 4 ] && echo "missing args" >&2 && return 1
    ../target/debug/zokrates batch --from_curve=$1 --to_curve=$2 --from_1=$3 --from_2=$4
}

err() {
    echo "Possible commands: build, unbuild, clean, compile, setup, witness, generate, verify, move, batch"
}

main() {
    local cmd; cmd=$1; shift
    [ -z "$cmd" ] && err && return 1
    [ $cmd != build ] \
        && [ $cmd != unbuild ] \
        && [ $cmd != clean ] \
        && [ $cmd != compile ] \
        && [ $cmd != setup ] \
        && [ $cmd != witness ] \
        && [ $cmd != generate ] \
        && [ $cmd != verify ] \
        && [ $cmd != move ] \
        && [ $cmd != batch ] \
        && err && return 1
    $cmd "$@"
}

main "$@"
